server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
jwt:
  secretKey: jwtSecretKeyjwtSecretKeyjwtSecretKeyjwtSecretKeyjwtSecretKey