server:
  port: 9494

spring:
  application:
    name: usertimeline-service

  data:
    mongodb:
      authentication-database: admin
      uuid-representation: standard
      database: usertimeline
      port: 27017
      host: localhost

  cloud:
    function:
      definition: consumer;register
    stream:
      bindings:
        consumer-in-0:
          destination: post-topic
          group: post-group
          consumer:
            client-id: post-id
        register-in-0:
          destination: register-topic
          group: register-group
          consumer:
            client-id: register-id
    config:
      enabled: false

#logging:
#  level:
#    org.springframework.cloud.stream: DEBUG
#    org.apache.kafka: DEBUG


