server:
  port: 9494

spring:
  application:
    name: usertimeline-service

  data:
    mongodb:
      authentication-database: admin
      uuid-representation: standard
      database: usertimeline
      port: 27017
      host: localhost

  cloud:
    function:
      definition: consumer;register
    stream:
      bindings:
        consumer-in-0:
          destination: post-user-topic
        register-in-0:
          destination: register-user-topic
    config:
      enabled: false