server:
  port: 9292

spring:
  application:
    name: hometimeline-service

  data:
    mongodb:
      authentication-database: admin
      uuid-representation: standard
      database: hometimeline
      port: 27017
      host: localhost

    config:
      enabled: false

  cloud:
    function:
      definition: post;register;follow
    config:
      enabled: false
    stream:
      bindings:
        post-in-0:
          destination: post-home-topic
        register-in-0:
          destination: register-home-topic
        follow-in-0:
          destination: follow-topic